export const KINDS = {

  CAT_BYC0010: 'catCRRT_DATA_BYC0010',
  DOCUMENT_TYPE: 'catCRRT_DOCUMENT_TYPE',

  // ACCESIBILIDAD
  AREAS_GEOGRAFICAS: 'astCUENTA_AREAS_GEOGRAFICAS',
  TAGGING_PLAN: 'catCRRT_TAGGING_PLAN',

  // POSTMESSAGES
  POST_APPREADY : 'catCRRT_POST_APPREADY',
  POST_APPFINISH: 'catCRRT_POST_APPFINISH'
};
